// Generated by ./gradlew :poker-server:generateProtocolTypes -- do not edit by hand.
// Regenerate after any change to the Kotlin protocol; never hand-merge this file.

export type ProtocolVersion = 4;

export type ClientMessage = Act | CreateRoom | Hello | JoinRoom | OfferRematch;

export interface Act {
  type: "Act";
  handNumber: number;
  actionSequence: number;
  action: PlayerAction;
}

export type PlayerAction = AllIn | Bet | Call | Check | Fold | Raise;

export interface AllIn {
  type: "AllIn";
  seat: number;
}

export interface Bet {
  type: "Bet";
  seat: number;
  to: number;
}

export interface Call {
  type: "Call";
  seat: number;
}

export interface Check {
  type: "Check";
  seat: number;
}

export interface Fold {
  type: "Fold";
  seat: number;
}

export interface Raise {
  type: "Raise";
  seat: number;
  to: number;
}

export interface CreateRoom {
  type: "CreateRoom";
}

export interface Hello {
  type: "Hello";
  deviceId: string | null;
  protocolVersion: number;
}

export interface JoinRoom {
  type: "JoinRoom";
  code: string;
}

export interface OfferRematch {
  type: "OfferRematch";
}

export type ServerMessage = ActedForAbsent | DuelFinished | Events | Failure | OpponentPresence | Rejected | RematchOffered | RoomJoined | Snapshot | Welcome | YourTurn;

export interface ActedForAbsent {
  type: "ActedForAbsent";
  seat: number;
  handNumber: number;
  actionSequence: number;
  action: ActionType;
}

export type ActionType = "FOLD" | "CHECK" | "CALL" | "BET" | "RAISE" | "ALL_IN";

export interface DuelFinished {
  type: "DuelFinished";
  outcome: DuelOutcome;
}

export interface DuelOutcome {
  winner: number | null;
  handsPlayed: number;
  finalStacks: readonly number[];
}

export interface Events {
  type: "Events";
  events: readonly GameEvent[];
}

export type GameEvent = ActionOn | PlayerAllIn | PlayerBet | PlayerCalled | PlayerChecked | PlayerFolded | PlayerRaised | BlindPosted | BettingRoundEnded | HandFinished | HandRevealed | PotAwarded | ShowdownReached | StreetDealt | UncalledBetReturned | HandStarted | HoleCardsDealt;

export interface ActionOn {
  type: "ActionOn";
  sequence: number;
  seat: number;
}

export interface PlayerAllIn {
  type: "PlayerAllIn";
  sequence: number;
  seat: number;
  to: number;
}

export interface PlayerBet {
  type: "PlayerBet";
  sequence: number;
  seat: number;
  to: number;
}

export interface PlayerCalled {
  type: "PlayerCalled";
  sequence: number;
  seat: number;
  to: number;
}

export interface PlayerChecked {
  type: "PlayerChecked";
  sequence: number;
  seat: number;
}

export interface PlayerFolded {
  type: "PlayerFolded";
  sequence: number;
  seat: number;
}

export interface PlayerRaised {
  type: "PlayerRaised";
  sequence: number;
  seat: number;
  to: number;
}

export interface BlindPosted {
  type: "BlindPosted";
  sequence: number;
  seat: number;
  to: number;
  isBigBlind: boolean;
}

export interface BettingRoundEnded {
  type: "BettingRoundEnded";
  sequence: number;
  street: Street;
}

export type Street = "PREFLOP" | "FLOP" | "TURN" | "RIVER" | "SHOWDOWN" | "COMPLETE";

export interface HandFinished {
  type: "HandFinished";
  sequence: number;
}

export interface HandRevealed {
  type: "HandRevealed";
  sequence: number;
  seat: number;
  cards: readonly string[];
}

export interface PotAwarded {
  type: "PotAwarded";
  sequence: number;
  seat: number;
  amount: number;
}

export interface ShowdownReached {
  type: "ShowdownReached";
  sequence: number;
}

export interface StreetDealt {
  type: "StreetDealt";
  sequence: number;
  street: Street;
  cards: readonly string[];
}

export interface UncalledBetReturned {
  type: "UncalledBetReturned";
  sequence: number;
  seat: number;
  amount: number;
}

export interface HandStarted {
  type: "HandStarted";
  sequence: number;
  handNumber: number;
  buttonSeat: number;
  smallBlind: number;
  bigBlind: number;
  stacks: readonly number[];
}

export interface HoleCardsDealt {
  type: "HoleCardsDealt";
  sequence: number;
  seat: number;
  cards: readonly string[];
}

export interface Failure {
  type: "Failure";
  error: ProtocolError;
}

export type ProtocolError = "UNKNOWN_MESSAGE" | "MALFORMED_MESSAGE" | "VERSION_MISMATCH" | "NOT_YOUR_TURN" | "UNKNOWN_ROOM" | "ROOM_FULL" | "NOT_IN_DUEL" | "DUEL_PAUSED" | "FRAME_LIMIT_EXCEEDED" | "REMATCH_UNAVAILABLE";

export interface OpponentPresence {
  type: "OpponentPresence";
  presence: SeatPresence;
  graceRemainingMillis: number | null;
}

export type SeatPresence = "PRESENT" | "AWAY" | "ABSENT";

export interface Rejected {
  type: "Rejected";
  rejection: Rejection;
}

export type Rejection = ActionNotAllowed | AmountTooLarge | AmountTooSmall | HandComplete | NotYourTurn;

export interface ActionNotAllowed {
  type: "ActionNotAllowed";
  attempted: ActionType;
  allowed: readonly ActionType[];
}

export interface AmountTooLarge {
  type: "AmountTooLarge";
  attempted: number;
  maximum: number;
}

export interface AmountTooSmall {
  type: "AmountTooSmall";
  attempted: number;
  minimum: number;
}

export interface HandComplete {
  type: "HandComplete";
}

export interface NotYourTurn {
  type: "NotYourTurn";
  seatToAct: number | null;
}

export interface RematchOffered {
  type: "RematchOffered";
  seat: number;
}

export interface RoomJoined {
  type: "RoomJoined";
  code: string;
  seat: number;
}

export interface Snapshot {
  type: "Snapshot";
  view: PlayerView;
}

export interface PlayerView {
  viewerSeat: number;
  handNumber: number;
  buttonSeat: number;
  street: Street;
  board: Board;
  pot: number;
  betToMatch: number;
  minRaiseTo: number;
  seatToAct: number | null;
  smallBlind: number;
  bigBlind: number;
  seats: readonly SeatView[];
}

export interface Board {
  cards: readonly string[];
}

export interface SeatView {
  index: number;
  stack: number;
  committedThisStreet: number;
  committedThisHand: number;
  hasFolded: boolean;
  isAllIn: boolean;
  holeCards: readonly string[];
}

export interface Welcome {
  type: "Welcome";
  deviceId: string;
  protocolVersion: number;
}

export interface YourTurn {
  type: "YourTurn";
  handNumber: number;
  actionSequence: number;
  legalActions: LegalActions;
}

export interface LegalActions {
  seat: number;
  allowed: readonly ActionType[];
  callTo: number;
  minBetTo: number;
  minRaiseTo: number;
  allInTo: number;
}
