package duels.poker.server.duel

import duels.poker.engine.duel.DuelFormat
import duels.poker.engine.duel.DuelOutcome
import duels.poker.engine.duel.EndCondition
import duels.poker.server.session.PlayerId
import java.time.Instant
import java.util.UUID

/**
 * A finished duel: which duel, which two profiles sat in it, when it ran, and the outcome.
 *
 * `FinishedDuel` is the value the write path takes: it is the only input to persistence,
 * and validation at construction ensures an impossible duel cannot reach the database.
 *
 * @param id the duel row's primary key and the write path's idempotency key (TASK-021009).
 *   Generated by the duel runner, never by the database.
 * @param format the end condition's label: "FREEZEOUT" or "FIXED_HANDS". The label is the name
 *   only; it carries no data about blind levels or hand counts, per DEC-001.
 * @param startedAt the instant the duel started, supplied by the caller.
 * @param finishedAt the instant the duel finished, supplied by the caller.
 * @param seats the two players, indexed by seat number — seats[0] is the player the engine
 *   calls seat 0. That is what lets TASK-021005 pair a CoinDeltas.forSeat(seat) with a profile
 *   without re-deriving anything. Each PlayerId.value is the text form of a player.id UUID.
 * @param outcome the engine's result: who won, how many hands played, and final stacks.
 */
public data class FinishedDuel(
    val id: UUID,
    val format: String,
    val startedAt: Instant,
    val finishedAt: Instant,
    val seats: List<PlayerId>,
    val outcome: DuelOutcome,
) {
    init {
        require(seats.size == 2) { "a duel has exactly two seats, got ${seats.size}" }
        require(seats[0] != seats[1]) { "one player cannot occupy both seats" }
        require(format.isNotBlank()) { "a duel format label must not be blank" }
        require(!finishedAt.isBefore(startedAt)) { "a duel cannot finish before it started" }
    }
}

/**
 * Maps a duel format to its label for persistence.
 *
 * This function has no `else` branch, so a third end condition stops the file compiling
 * instead of silently storing the wrong label. The label is the end condition's name only.
 *
 * @param format the duel format to label
 * @return the format's label: "FREEZEOUT" or "FIXED_HANDS"
 */
public fun formatLabel(format: DuelFormat): String =
    when (format.endCondition) {
        is EndCondition.Freezeout -> "FREEZEOUT"
        is EndCondition.FixedHands -> "FIXED_HANDS"
    }
